### ISSUE TITLE
Test the Valid Moves Generation

### ISSUE THREAD

**Issue by lukassobotik** [lukassobotik/SightlessKnight#4]
Create a [**Perft Function**](https://www.chessprogramming.org/Perft), compare it with the [**Expected Results**](https://www.chessprogramming.org/Perft_Results) and fix any errors that might occur.

**Comment by PuckyEU** [comment]
After the latest commit ([**Perft Test Implementation**](../commit/6ad283d383a36cf64e91938f63207b3014681ebc)), there are still some things that do not work. Currently, I've found that some of the issues on the start position and depth 5 are most likely produced by _en passant_ moves. Another bottleneck could be promotion moves.
